---
- name: Fetch Request From ServiceNow
  hosts: host
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: tasks/fetch_servicenow.yml


- name: Create Linux User
  hosts: host
  become: yes

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: tasks/create_linux_user.yml


- name: Update ServiceNow
  hosts: host
  gather_facts: false

  vars_files:
    - vars.yml

  tasks:
    - include_tasks: tasks/update_servicenow.yml
