---
- name: Update apt package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Upgrade installed packages
  apt:
    upgrade: dist

- name: Check if reboot required
  stat:
    path: /var/run/reboot-required
  register: reboot_required

- name: Reboot server if required
  reboot:
    msg: "Rebooting after patching"
    reboot_timeout: 300
  when: reboot_required.stat.exists

- name: Wait for connection after reboot
  wait_for_connection:
    timeout: 300
    delay: 10
  when: reboot_required.stat.exists
